server_path = "/home/alina/задача_1.1/"
balance_file_name = f"{server_path}ft_balance_f.csv"
balance_file_name = f"{server_path}ft_balance_f.csv"
posting_file_name = f"{server_path}ft_posting_f.csv"
account_file_name = f"{server_path}md_account_d.csv"
currency_file_name = f"{server_path}md_currency_d.csv"
exchange_rate_file_name = f"{server_path}md_exchange_rate_d.csv"
ledger_account_file_name = f"{server_path}md_ledger_account_s.csv"